name: Build .NET Core backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Random word for kicks'
        # Default value if no value is explicitly provided
        default: 'Chocolate'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./projects/health-wise-api/src/HealthWiseBackend.API
    - name: Build
      run: dotnet build ./projects/health-wise-api/src/HealthWiseBackend.API --configuration Release --no-restore
